// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: rides.proto

package src

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartRideRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RiderId      string `protobuf:"bytes,1,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	DriverId     string `protobuf:"bytes,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	StartLat     string `protobuf:"bytes,3,opt,name=start_lat,json=startLat,proto3" json:"start_lat,omitempty"`
	StartLong    string `protobuf:"bytes,4,opt,name=start_long,json=startLong,proto3" json:"start_long,omitempty"`
	EndLat       string `protobuf:"bytes,5,opt,name=end_lat,json=endLat,proto3" json:"end_lat,omitempty"`
	EndLong      string `protobuf:"bytes,6,opt,name=end_long,json=endLong,proto3" json:"end_long,omitempty"`
	RideDistance string `protobuf:"bytes,7,opt,name=ride_distance,json=rideDistance,proto3" json:"ride_distance,omitempty"`
	RideDuration string `protobuf:"bytes,8,opt,name=ride_duration,json=rideDuration,proto3" json:"ride_duration,omitempty"`
}

func (x *StartRideRequest) Reset() {
	*x = StartRideRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rides_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartRideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRideRequest) ProtoMessage() {}

func (x *StartRideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rides_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRideRequest.ProtoReflect.Descriptor instead.
func (*StartRideRequest) Descriptor() ([]byte, []int) {
	return file_rides_proto_rawDescGZIP(), []int{0}
}

func (x *StartRideRequest) GetRiderId() string {
	if x != nil {
		return x.RiderId
	}
	return ""
}

func (x *StartRideRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *StartRideRequest) GetStartLat() string {
	if x != nil {
		return x.StartLat
	}
	return ""
}

func (x *StartRideRequest) GetStartLong() string {
	if x != nil {
		return x.StartLong
	}
	return ""
}

func (x *StartRideRequest) GetEndLat() string {
	if x != nil {
		return x.EndLat
	}
	return ""
}

func (x *StartRideRequest) GetEndLong() string {
	if x != nil {
		return x.EndLong
	}
	return ""
}

func (x *StartRideRequest) GetRideDistance() string {
	if x != nil {
		return x.RideDistance
	}
	return ""
}

func (x *StartRideRequest) GetRideDuration() string {
	if x != nil {
		return x.RideDuration
	}
	return ""
}

type StartRideResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RideId  string `protobuf:"bytes,1,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	Code    int32  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *StartRideResponse) Reset() {
	*x = StartRideResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rides_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartRideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRideResponse) ProtoMessage() {}

func (x *StartRideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rides_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRideResponse.ProtoReflect.Descriptor instead.
func (*StartRideResponse) Descriptor() ([]byte, []int) {
	return file_rides_proto_rawDescGZIP(), []int{1}
}

func (x *StartRideResponse) GetRideId() string {
	if x != nil {
		return x.RideId
	}
	return ""
}

func (x *StartRideResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *StartRideResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type FindRideRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartLat  string `protobuf:"bytes,1,opt,name=start_lat,json=startLat,proto3" json:"start_lat,omitempty"`
	StartLong string `protobuf:"bytes,2,opt,name=start_long,json=startLong,proto3" json:"start_long,omitempty"`
}

func (x *FindRideRequest) Reset() {
	*x = FindRideRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rides_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindRideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRideRequest) ProtoMessage() {}

func (x *FindRideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rides_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRideRequest.ProtoReflect.Descriptor instead.
func (*FindRideRequest) Descriptor() ([]byte, []int) {
	return file_rides_proto_rawDescGZIP(), []int{2}
}

func (x *FindRideRequest) GetStartLat() string {
	if x != nil {
		return x.StartLat
	}
	return ""
}

func (x *FindRideRequest) GetStartLong() string {
	if x != nil {
		return x.StartLong
	}
	return ""
}

type FindRideResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RideId       string `protobuf:"bytes,1,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	DriverId     string `protobuf:"bytes,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	StartLat     string `protobuf:"bytes,3,opt,name=start_lat,json=startLat,proto3" json:"start_lat,omitempty"`
	StartLong    string `protobuf:"bytes,4,opt,name=start_long,json=startLong,proto3" json:"start_long,omitempty"`
	EndLat       string `protobuf:"bytes,5,opt,name=end_lat,json=endLat,proto3" json:"end_lat,omitempty"`
	EndLong      string `protobuf:"bytes,6,opt,name=end_long,json=endLong,proto3" json:"end_long,omitempty"`
	RideDistance string `protobuf:"bytes,7,opt,name=ride_distance,json=rideDistance,proto3" json:"ride_distance,omitempty"`
	RideDuration string `protobuf:"bytes,8,opt,name=ride_duration,json=rideDuration,proto3" json:"ride_duration,omitempty"`
	Code         int32  `protobuf:"varint,9,opt,name=code,proto3" json:"code,omitempty"`
	Message      string `protobuf:"bytes,10,opt,name=message,proto3" json:"message,omitempty"` // price will be calculated by company prices
}

func (x *FindRideResponse) Reset() {
	*x = FindRideResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rides_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindRideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRideResponse) ProtoMessage() {}

func (x *FindRideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rides_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRideResponse.ProtoReflect.Descriptor instead.
func (*FindRideResponse) Descriptor() ([]byte, []int) {
	return file_rides_proto_rawDescGZIP(), []int{3}
}

func (x *FindRideResponse) GetRideId() string {
	if x != nil {
		return x.RideId
	}
	return ""
}

func (x *FindRideResponse) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *FindRideResponse) GetStartLat() string {
	if x != nil {
		return x.StartLat
	}
	return ""
}

func (x *FindRideResponse) GetStartLong() string {
	if x != nil {
		return x.StartLong
	}
	return ""
}

func (x *FindRideResponse) GetEndLat() string {
	if x != nil {
		return x.EndLat
	}
	return ""
}

func (x *FindRideResponse) GetEndLong() string {
	if x != nil {
		return x.EndLong
	}
	return ""
}

func (x *FindRideResponse) GetRideDistance() string {
	if x != nil {
		return x.RideDistance
	}
	return ""
}

func (x *FindRideResponse) GetRideDuration() string {
	if x != nil {
		return x.RideDuration
	}
	return ""
}

func (x *FindRideResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *FindRideResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CancelRideRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RideId string `protobuf:"bytes,1,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
}

func (x *CancelRideRequest) Reset() {
	*x = CancelRideRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rides_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelRideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRideRequest) ProtoMessage() {}

func (x *CancelRideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rides_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRideRequest.ProtoReflect.Descriptor instead.
func (*CancelRideRequest) Descriptor() ([]byte, []int) {
	return file_rides_proto_rawDescGZIP(), []int{4}
}

func (x *CancelRideRequest) GetRideId() string {
	if x != nil {
		return x.RideId
	}
	return ""
}

type CancelRideResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CancelRideResponse) Reset() {
	*x = CancelRideResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rides_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelRideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRideResponse) ProtoMessage() {}

func (x *CancelRideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rides_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRideResponse.ProtoReflect.Descriptor instead.
func (*CancelRideResponse) Descriptor() ([]byte, []int) {
	return file_rides_proto_rawDescGZIP(), []int{5}
}

func (x *CancelRideResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CancelRideResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EndRideRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RideId string `protobuf:"bytes,1,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
}

func (x *EndRideRequest) Reset() {
	*x = EndRideRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rides_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndRideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndRideRequest) ProtoMessage() {}

func (x *EndRideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rides_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndRideRequest.ProtoReflect.Descriptor instead.
func (*EndRideRequest) Descriptor() ([]byte, []int) {
	return file_rides_proto_rawDescGZIP(), []int{6}
}

func (x *EndRideRequest) GetRideId() string {
	if x != nil {
		return x.RideId
	}
	return ""
}

type EndRideResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *EndRideResponse) Reset() {
	*x = EndRideResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rides_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndRideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndRideResponse) ProtoMessage() {}

func (x *EndRideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rides_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndRideResponse.ProtoReflect.Descriptor instead.
func (*EndRideResponse) Descriptor() ([]byte, []int) {
	return file_rides_proto_rawDescGZIP(), []int{7}
}

func (x *EndRideResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *EndRideResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateRideRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RideId    string `protobuf:"bytes,1,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	DriverId  string `protobuf:"bytes,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	StartLat  string `protobuf:"bytes,3,opt,name=start_lat,json=startLat,proto3" json:"start_lat,omitempty"`
	StartLong string `protobuf:"bytes,4,opt,name=start_long,json=startLong,proto3" json:"start_long,omitempty"`
}

func (x *CreateRideRequest) Reset() {
	*x = CreateRideRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rides_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRideRequest) ProtoMessage() {}

func (x *CreateRideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rides_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRideRequest.ProtoReflect.Descriptor instead.
func (*CreateRideRequest) Descriptor() ([]byte, []int) {
	return file_rides_proto_rawDescGZIP(), []int{8}
}

func (x *CreateRideRequest) GetRideId() string {
	if x != nil {
		return x.RideId
	}
	return ""
}

func (x *CreateRideRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *CreateRideRequest) GetStartLat() string {
	if x != nil {
		return x.StartLat
	}
	return ""
}

func (x *CreateRideRequest) GetStartLong() string {
	if x != nil {
		return x.StartLong
	}
	return ""
}

type CreateRideResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CreateRideResponse) Reset() {
	*x = CreateRideResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rides_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRideResponse) ProtoMessage() {}

func (x *CreateRideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rides_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRideResponse.ProtoReflect.Descriptor instead.
func (*CreateRideResponse) Descriptor() ([]byte, []int) {
	return file_rides_proto_rawDescGZIP(), []int{9}
}

func (x *CreateRideResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateRideResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_rides_proto protoreflect.FileDescriptor

var file_rides_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x72, 0x69, 0x64, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x72,
	0x69, 0x64, 0x65, 0x73, 0x22, 0x84, 0x02, 0x0a, 0x10, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x69,
	0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x69, 0x64,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x69, 0x64,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x6c, 0x61, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x74, 0x61, 0x72, 0x74, 0x4c, 0x61, 0x74, 0x12, 0x1d,
	0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x6c, 0x6f, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x4c, 0x6f, 0x6e, 0x67, 0x12, 0x17, 0x0a,
	0x07, 0x65, 0x6e, 0x64, 0x5f, 0x6c, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x65, 0x6e, 0x64, 0x4c, 0x61, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x6c, 0x6f,
	0x6e, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x4c, 0x6f, 0x6e,
	0x67, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x69, 0x64, 0x65, 0x5f, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x69, 0x64, 0x65, 0x44, 0x69,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x69, 0x64, 0x65, 0x5f, 0x64,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72,
	0x69, 0x64, 0x65, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x5a, 0x0a, 0x11, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x52, 0x69, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x17, 0x0a, 0x07, 0x72, 0x69, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x72, 0x69, 0x64, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x4d, 0x0a, 0x0f, 0x46, 0x69, 0x6e, 0x64, 0x52,
	0x69, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x5f, 0x6c, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x4c, 0x61, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x5f, 0x6c, 0x6f, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x4c, 0x6f, 0x6e, 0x67, 0x22, 0xb0, 0x02, 0x0a, 0x10, 0x46, 0x69, 0x6e, 0x64, 0x52,
	0x69, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x72,
	0x69, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x69,
	0x64, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x6c, 0x61, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x74, 0x61, 0x72, 0x74, 0x4c, 0x61, 0x74, 0x12, 0x1d,
	0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x6c, 0x6f, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x4c, 0x6f, 0x6e, 0x67, 0x12, 0x17, 0x0a,
	0x07, 0x65, 0x6e, 0x64, 0x5f, 0x6c, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x65, 0x6e, 0x64, 0x4c, 0x61, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x6c, 0x6f,
	0x6e, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x4c, 0x6f, 0x6e,
	0x67, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x69, 0x64, 0x65, 0x5f, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x69, 0x64, 0x65, 0x44, 0x69,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x69, 0x64, 0x65, 0x5f, 0x64,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72,
	0x69, 0x64, 0x65, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x2c, 0x0a, 0x11, 0x43, 0x61, 0x6e,
	0x63, 0x65, 0x6c, 0x52, 0x69, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17,
	0x0a, 0x07, 0x72, 0x69, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x72, 0x69, 0x64, 0x65, 0x49, 0x64, 0x22, 0x42, 0x0a, 0x12, 0x43, 0x61, 0x6e, 0x63, 0x65,
	0x6c, 0x52, 0x69, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x29, 0x0a, 0x0e, 0x45,
	0x6e, 0x64, 0x52, 0x69, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x72, 0x69, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x72, 0x69, 0x64, 0x65, 0x49, 0x64, 0x22, 0x3f, 0x0a, 0x0f, 0x45, 0x6e, 0x64, 0x52, 0x69, 0x64,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x85, 0x01, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x52, 0x69, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x72, 0x69, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x72, 0x69, 0x64, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x72, 0x69, 0x76, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x6c, 0x61, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x74, 0x61, 0x72, 0x74, 0x4c, 0x61, 0x74,
	0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x6c, 0x6f, 0x6e, 0x67, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x4c, 0x6f, 0x6e, 0x67, 0x22,
	0x42, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x69, 0x64, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x32, 0xd0, 0x02, 0x0a, 0x05, 0x52, 0x69, 0x64, 0x65, 0x73, 0x12, 0x3f, 0x0a,
	0x08, 0x46, 0x69, 0x6e, 0x64, 0x52, 0x69, 0x64, 0x65, 0x12, 0x16, 0x2e, 0x72, 0x69, 0x64, 0x65,
	0x73, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x52, 0x69, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x17, 0x2e, 0x72, 0x69, 0x64, 0x65, 0x73, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x52, 0x69,
	0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x40,
	0x0a, 0x09, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x69, 0x64, 0x65, 0x12, 0x17, 0x2e, 0x72, 0x69,
	0x64, 0x65, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x69, 0x64, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x72, 0x69, 0x64, 0x65, 0x73, 0x2e, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x52, 0x69, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x43, 0x0a, 0x0a, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x52, 0x69, 0x64, 0x65, 0x12, 0x18,
	0x2e, 0x72, 0x69, 0x64, 0x65, 0x73, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x52, 0x69, 0x64,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x72, 0x69, 0x64, 0x65, 0x73,
	0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x52, 0x69, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x07, 0x45, 0x6e, 0x64, 0x52, 0x69, 0x64, 0x65,
	0x12, 0x15, 0x2e, 0x72, 0x69, 0x64, 0x65, 0x73, 0x2e, 0x45, 0x6e, 0x64, 0x52, 0x69, 0x64, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x72, 0x69, 0x64, 0x65, 0x73, 0x2e,
	0x45, 0x6e, 0x64, 0x52, 0x69, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x43, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x69, 0x64, 0x65, 0x12,
	0x18, 0x2e, 0x72, 0x69, 0x64, 0x65, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x69,
	0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x72, 0x69, 0x64, 0x65,
	0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x69, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x77, 0x7a, 0x73, 0x6c, 0x72, 0x33, 0x32, 0x31, 0x2f, 0x72, 0x6f,
	0x61, 0x64, 0x5f, 0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2f, 0x72, 0x69, 0x64, 0x65, 0x73, 0x2f, 0x73, 0x72, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_rides_proto_rawDescOnce sync.Once
	file_rides_proto_rawDescData = file_rides_proto_rawDesc
)

func file_rides_proto_rawDescGZIP() []byte {
	file_rides_proto_rawDescOnce.Do(func() {
		file_rides_proto_rawDescData = protoimpl.X.CompressGZIP(file_rides_proto_rawDescData)
	})
	return file_rides_proto_rawDescData
}

var file_rides_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_rides_proto_goTypes = []interface{}{
	(*StartRideRequest)(nil),   // 0: rides.StartRideRequest
	(*StartRideResponse)(nil),  // 1: rides.StartRideResponse
	(*FindRideRequest)(nil),    // 2: rides.FindRideRequest
	(*FindRideResponse)(nil),   // 3: rides.FindRideResponse
	(*CancelRideRequest)(nil),  // 4: rides.CancelRideRequest
	(*CancelRideResponse)(nil), // 5: rides.CancelRideResponse
	(*EndRideRequest)(nil),     // 6: rides.EndRideRequest
	(*EndRideResponse)(nil),    // 7: rides.EndRideResponse
	(*CreateRideRequest)(nil),  // 8: rides.CreateRideRequest
	(*CreateRideResponse)(nil), // 9: rides.CreateRideResponse
}
var file_rides_proto_depIdxs = []int32{
	2, // 0: rides.Rides.FindRide:input_type -> rides.FindRideRequest
	0, // 1: rides.Rides.StartRide:input_type -> rides.StartRideRequest
	4, // 2: rides.Rides.CancelRide:input_type -> rides.CancelRideRequest
	6, // 3: rides.Rides.EndRide:input_type -> rides.EndRideRequest
	8, // 4: rides.Rides.CreateRide:input_type -> rides.CreateRideRequest
	3, // 5: rides.Rides.FindRide:output_type -> rides.FindRideResponse
	1, // 6: rides.Rides.StartRide:output_type -> rides.StartRideResponse
	5, // 7: rides.Rides.CancelRide:output_type -> rides.CancelRideResponse
	7, // 8: rides.Rides.EndRide:output_type -> rides.EndRideResponse
	9, // 9: rides.Rides.CreateRide:output_type -> rides.CreateRideResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rides_proto_init() }
func file_rides_proto_init() {
	if File_rides_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rides_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartRideRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rides_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartRideResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rides_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindRideRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rides_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindRideResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rides_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelRideRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rides_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelRideResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rides_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EndRideRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rides_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EndRideResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rides_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRideRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rides_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRideResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rides_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rides_proto_goTypes,
		DependencyIndexes: file_rides_proto_depIdxs,
		MessageInfos:      file_rides_proto_msgTypes,
	}.Build()
	File_rides_proto = out.File
	file_rides_proto_rawDesc = nil
	file_rides_proto_goTypes = nil
	file_rides_proto_depIdxs = nil
}
