name: road_runner
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0-366.0.dev'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  auto_route: ^5.0.4
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  intl: any
  freezed_annotation: ^2.2.0
  mocktail: ^0.3.0
  users_repository:
    path: ./packages/users_repository
  fpdart: ^0.5.0
  change_app_package_name: ^1.1.0
  oauth2: ^2.0.1

dev_dependencies:
  analyzer: ^5.7.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  auto_route_generator: ^5.0.3
  flutter_gen_runner: ^5.2.0
  flutter_launcher_icons: ^0.12.0
  freezed: ^2.3.2

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

flutter_icons:
  ios: true
  image_path: "assets/icons/app_icon.png"
  remove_alpha_ios: true
