version: '3.9'
services:
  users:
    build:
      context: .
    environment:
      - DEV_MODE=PROD
    ports:
      - '8080:8080'
    volumes:
      - ./src:/server/src
    depends_on:
      - scylladb
  scylladb:
    image: scylladb/scylla:5.1
    ports:
      - '8081:8081'