version: '3.9'
services:
  users:
    build:
      context: .
    environment:
      GIN_MODE: debug
    ports:
      - '8080:8080'
    volumes:
      - ./:/users
  ravendb:
    image: ravendb/ravendb:5.4-ubuntu-latest
    ports:
      - '8081:8080'
    volumes:
      - ./ravendb:/ravendb