version: '3.9'
services:
  scylladb:
    image: scylladb/scylla:5.1
    ports:
      - '9042:9042'
    healthcheck:
      test: [ "CMD-SHELL", "[ $$(nodetool statusgossip) = running ]" ]
      interval: 30s
      timeout: 10s
      retries: 5
  users:
    build:
      context: .
      dockerfile: dev.Dockerfile
    environment:
      - DEV_MODE=DEV
    ports:
      - '8080:8080'
    volumes:
      - ./src:/server/users
    depends_on:
      scylladb:
        condition: service_healthy