version: '3.9'
services:
  users:
    build:
      context: .
      dockerfile: dev.Dockerfile
    environment:
      - DEV_MODE=DEV
    ports:
      - '8080:8080'
    volumes:
      - ./:/server/users
  scylladb:
    image: scylladb/scylla:5.1
    ports:
      - '8081:8081'
    volumes:
      - ./ravendb:/ravendb