version: '3.9'
services:
  users:
    build:
      context: .
    environment:
      - DEV_MODE=PROD
    ports:
      - '8080:8080'
    volumes:
      - ./:/users
  scylladb:
    image: scylladb/scylla:5.1
    ports:
      - '8081:8081'
    volumes:
      - ./ravendb:/ravendb