name: main
on: [ push, pull_request ]

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      coverage_excludes: "*.g.dart *.freezed.dart *.gen.dart" # defaults to "" (none)
      flutter_channel: master
      flutter_version: 3.9.0-1.0.pre.33
      working_directory: client
      min_coverage: 0

  visualize:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter_version: 3.9.0-1.0.pre.33
          channel: master
      - name: Generate Dependency Graph
        with:
          flutter_version: 3.9.0-1.0.pre.33
          channel: master
        env:
          FLUTTER_DART_HOME: ${{ env.FLUTTER_HOME }}/bin/cache/dart-sdk/bin
          FLUTTER_PUB_CACHE: ${{env.FLUTTER_HOME}}/.pub-cache/bin
        run: |
          flutter pub global activate pubviz
          echo $?
          export PATH=$PATH:$FLUTTER_DART_HOME
          export PATH=$PATH:$FLUTTER_PUB_CACHE
          pubviz print -d > pubviz.html

      - name: Upload Dependency Graph
        uses: actions/upload-artifact@v1
        with:
          name: dependency-graph
          path: pubviz.html
          flutter_version: 3.9.0-1.0.pre.33
          channel: master
